# Flutter build
variables:
  projectDirectory: ''
trigger:
  - master
jobs:
  - job: Android
    pool:
      vmImage: 'macOS-10.14'
    steps:
      - task: FlutterInstall@0
      - task: FlutterBuild@0
        inputs:
          target: apk
          projectDirectory: $(projectDirectory)

      - task: AndroidSigning@3
        displayName: 'Signing and aligning APK file(s) **/*.apk'
        inputs:
          apkFiles: '**/*.apk'
          apksign: true
          apksignerKeystoreFile: 'demo.jks'
          apksignerKeystorePassword: $(KeyStorePassword)
          apksignerKeystoreAlias: $(KeyAlias)
          apksignerKeyPassword: $(KeyPassword)

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'app/build/outputs/apk/release'
          ArtifactName: 'drop'
          publishLocation: 'Container'